### ISSUE TITLE
上一篇和下一篇链接不上

### ISSUE THREAD

**Issue by azure2870** [pianfan/pianfan.github.io#14]
不知道什么原因，按照文章来的

**Comment by pianfan** [comment]
把你的_config.yml文件中的url改为https://azure2870.github.io/zyf.github.io试试

**Comment by pianfan** [comment]
把你的 _config.yml 文件中的 url 改为 https://azure2870.github.io/zyf.github.io 试试

**Comment by azure2870** [comment]
还是不行，会变成这样https://azure2870.github.io/zyf.github.io/zyf.github.io/letter_to_you/，多了/zyf.github.io/这个，感觉是不是
![image](https://github.com/user-attachments/assets/5002f5bd-1bb7-43bb-94dc-99e839574c1a)代码的原因。看不懂。

**Comment by azure2870** [comment]
成功了，可能是网页没有更新，没有反应，谢谢博主！
