### ISSUE TITLE
请问能否在文章页不显示左边的栏目？

### ISSUE THREAD

**Issue by Sophus-PHLin** [pianfan/pianfan.github.io#6]
如题，文章页左边"xxx's homepage"占了很大一部分，请问怎么改代码让他消失？
我不是计算机专业的，麻烦你了orz

**Comment by pianfan** [comment]
不建议这么做，这种设计是经过了成熟考虑的。因为如果文章占满整个电脑屏幕会比较难以阅读，可能页面效果反而更差（参考其他博客页面，文章旁边基本都有边栏啥的）。另外这玩意其实是根据页面宽度动态调整的，当页面窄到一定程度时，它会跑到页面上方，并不会影响阅读体验。
如果你非要让它消失，一个简单粗暴的方法是把_layouts/post.html中第2行的layout: default注释掉，但是这样会导致页面样式缺失。你可以先试着改一下看看效果，如果仍然觉得让它消失会好一点，可以再向我询问如何保留原先的样式。
________________________________
发件人: PHLin ***@***.***>
发送时间: 2024年5月12日 15:35
收件人: pianfan/pianfan.github.io ***@***.***>
抄送: Subscribed ***@***.***>
主题: [pianfan/pianfan.github.io] 请问能否在文章页不显示左边的栏目？ (Issue #6)


如题，文章页左边"xxx's homepage"占了很大一部分，请问怎么改代码让他消失？
我不是计算机专业的，麻烦你了orz

―

**Comment by Sophus-PHLin** [comment]
我试了一下，确实出问题，那请问怎么把边栏缩小到页面的1/4?

**Comment by Sophus-PHLin** [comment]
另外字体似乎比较不好看，请问怎么设置中文字体simhei，英文字体calibri？

**Comment by pianfan** [comment]
这个在style.scss文件中的第322行，将30%改成25%即可。

________________________________
发件人: PHLin ***@***.***>
发送时间: 2024年5月12日 17:47
收件人: pianfan/pianfan.github.io ***@***.***>
抄送: Xiong Yunhan ***@***.***>; Comment ***@***.***>
主题: Re: [pianfan/pianfan.github.io] 请问能否在文章页不显示左边的栏目？ (Issue #6)


我试了一下，确实出问题，那请问怎么把边栏缩小到页面的1/4?

―

**Comment by pianfan** [comment]
1.
_sass<https://github.com/pianfan/pianfan.github.io/tree/main/_sass>/_variables.scss第23行$base-font: 后面那一长串改成calibri, simhei;

________________________________
发件人: PHLin ***@***.***>
发送时间: 2024年5月12日 17:54
收件人: pianfan/pianfan.github.io ***@***.***>
抄送: Xiong Yunhan ***@***.***>; Comment ***@***.***>
主题: Re: [pianfan/pianfan.github.io] 请问能否在文章页不显示左边的栏目？ (Issue #6)


另外字体似乎比较不好看，请问怎么设置中文字体simhei，英文字体calibri？

―

**Comment by Sophus-PHLin** [comment]
谢谢你的解答！
